# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Run Python Tests and Lint

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      if: always()

    - name: Install dev dependencies
      run: |
        pip install black mypy pytest typer

    - name: Lint with Black
      run: |
        python -m black . --check

    - name: Type check with mypy
      run: |
        python -m mypy . --strict

    - name: Set environment variables
      env:
        QUANDL_API_KEY: "${{ secrets.QUANDL_API_KEY }}"
        API_KEY: "${{secrets.AV_API_KEY}}"
        POLY_API_KEY: "${{secrets.POLY_API_KEY}}"
      run: echo "Environment variables set"

    - name: Test with pytest
      run: |
        python -m pytest -s tests

    - name: Upload test results
      if: always() 
      uses: actions/upload-artifact@v3
      with:
        name: pytest-results
        path: ./test-results/
